### ISSUE TITLE
hiding nitro upselling hides game quests

### ISSUE THREAD

**Issue by josephisticated** [D3SOX/complementary-discord-theme#4]
would it be possible to make a version that doesn't block it maybe? free stuff might be nice
thought of just editing the CSS but updating would be a problem, maybe a different branch?

**Comment by D3SOX** [comment]
Just add to your QuickCSS:

```css
[class^="questsContainer__"] {
  display: block !important;
}
```
